imports:
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Processing.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml' }
    - { resource: 'EXT:rmnd_headless/Configuration/RTE/Editor/Alignment.yaml' }
    - { resource: 'EXT:rmnd_headless/Configuration/RTE/Editor/FontSize.yaml' }
    - { resource: 'EXT:rmnd_headless/Configuration/RTE/Editor/Heading.yaml' }
    - { resource: 'EXT:rmnd_headless/Configuration/RTE/Editor/Table.yaml' }

editor:
  config:
    toolbar:
      items:
        - heading
        - '|'
        - fontSize
        - bold
        - italic
        - subscript
        - superscript
        - softhyphen
        - '|'
        - bulletedList
        - numberedList
        - alignment
        - '|'
        - findAndReplace
        - link
        - '|'
        - removeFormat
        - undo
        - redo
        - '|'
        - insertTable
        - '|'
        - specialCharacters
        - horizontalLine
        - sourceEditing
