services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Remind\Headless\:
    resource: '../Classes/*'
  Remind\Headless\Service\JsonService:
    shared: false
  Remind\Headless\Event\Listener\EnrichFileData:
    tags:
      -
        name: event.listener
